call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'

" Utility
Plug 'scrooloose/nerdtree'
Plug 'preservim/nerdcommenter'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'majutsushi/tagbar'
Plug 'yggdroot/indentline'
Plug 'mileszs/ack.vim'
Plug 'airblade/vim-gitgutter'
Plug 'ryanoasis/vim-devicons'
Plug 'qpkorr/vim-bufkill'

" Themes
Plug 'morhetz/gruvbox'
Plug 'haishanh/night-owl.vim'
Plug 'whatyouhide/vim-gotham'
Plug 'itchyny/lightline.vim'

" Languages
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
"Plug 'vim-python/python-syntax' "syntax highlighting

if has('nvim')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
endif

call plug#end()

" ---------------------------------------------------------------------
" KEY_BINDINGS
" ---------------------------------------------------------------------
source $HOME/repos/brianmoran/dotfiles/vim/general.vimrc
source $HOME/repos/brianmoran/dotfiles/vim/bindings.vimrc

" ---------------------------------------------------------------------
" FUNCTIONS
" ---------------------------------------------------------------------
function! ToggleSyntax()
    if (exists("g:syntax_on"))
        syntax off
    else
        syntax enable
    endif
endfunction

function! ToggleMouse()
    if &mouse == 'a'
        set mouse=
    else
        set mouse=a
    endif
endfunction

" ------------------------------------------------------------
" PLUGINS
" ------------------------------------------------------------
source $HOME/repos/brianmoran/dotfiles/vim/plugins.vimrc

